config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 # resources :dashboards
  resources :daily_totals
  get 'dashboards/get_usage', as:'dashboard'
  post 'update_usage' => 'dashboards#get_usage'
  root 'dashboards#get_usage'

  get 'totals' => 'daily_totals#index'
end

app/models/daily_total.rb
class DailyTotal < ActiveRecord::Base
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/daily_totals_controller.rb
class DailyTotalsController < ApplicationController
  before_action :set_daily_total, only: [:show, :edit, :update, :destroy]

  # GET /daily_totals
  # GET /daily_totals.json
  def index
    @daily_totals = DailyTotal.all
  end

  # GET /daily_totals/1
  # GET /daily_totals/1.json
  def show
  end

  # GET /daily_totals/new
  def new
    @daily_total = DailyTotal.new
  end

  # GET /daily_totals/1/edit
  def edit
  end

  # POST /daily_totals
  # POST /daily_totals.json
  def create
    @daily_total = DailyTotal.new(daily_total_params)

    respond_to do |format|
      if @daily_total.save
        format.html { redirect_to @daily_total, notice: 'Daily total was successfully created.' }
        format.json { render :show, status: :created, location: @daily_total }
      else
        format.html { render :new }
        format.json { render json: @daily_total.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /daily_totals/1
  # PATCH/PUT /daily_totals/1.json
  def update
    respond_to do |format|
      if @daily_total.update(daily_total_params)
        format.html { redirect_to @daily_total, notice: 'Daily total was successfully updated.' }
        format.json { render :show, status: :ok, location: @daily_total }
      else
        format.html { render :edit }
        format.json { render json: @daily_total.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /daily_totals/1
  # DELETE /daily_totals/1.json
  def destroy
    @daily_total.destroy
    respond_to do |format|
      format.html { redirect_to daily_totals_url, notice: 'Daily total was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily_total
      @daily_total = DailyTotal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def daily_total_params
      params.require(:daily_total).permit(:date, :new_card_regs, :daily_rx_users, :device_registrations, :device_activity, :peoplescanning, :items_scanned)
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  #before_action :set_dashboard, only: [:show, :edit, :update, :destroy]
before_filter :authenticate_user!

  require 'open-uri'
  require 'json'

  def get_usage
    @begin_date = (params[:begin_date])
    @end_date = (params[:end_date])
    if @begin_date.nil?
      check_dates # Check if dates are nil and populate if so
    end
    # byebug
    #  @begin_date = Date.strptime(@begin_date, '%m/%d/%Y').strftime("%Y%m%d")
    @begin_date = Date.strptime(@begin_date, '%m/%d/%Y').strftime("%Y%m%d")
    @end_date = Date.strptime(@end_date, '%m/%d/%Y').strftime("%Y%m%d")

    @status_lookup = "http://ebtshopper.jpma.com/Management/json/GetStatistics.php?begin=#{@begin_date}&end=#{@end_date}"
    @response = open(@status_lookup).read
    @usage_hash = JSON.parse @response
    @rxusage = @usage_hash["data"]["rxusage"]
    @devusage = @usage_hash["data"]["devusage"]
    #byebug
    @mrg = []
    @rxusage.each do |el1|
      @devusage.each do |el2|
        if el2['Name'] == el1['Name']
          @mrg.push(el1.merge(el2))
        end
      end
    end
    sum_usage
  end

  def check_dates
    @begin_date = Date.today.strftime('%m/%d/%Y')
    @end_date = Date.tomorrow.strftime('%m/%d/%Y')
  end

  def sum_usage
    @total_user_count = @mrg.inject(0) { |sum, hash| sum + hash["UserCount"] }
    @total_registration_count = @mrg.inject(0) { |sum, hash| sum + hash["RegistrationCount"] }
    @total_device_registrations_count = @mrg.inject(0) { |sum, hash| sum + hash["DeviceRegistrations"] }
    @total_device_activity_count = @mrg.inject(0) { |sum, hash| sum + hash["DeviceActivity"] }
  end


  # GET /dashboards
  # GET /dashboards.json
  def index
    @dashboards = Dashboard.all
  end


  # GET /dashboards/1
  # GET /dashboards/1.json
  def show
  end

  # GET /dashboards/new
  def new
    @dashboard = Dashboard.new
  end

  # GET /dashboards/1/edit
  def edit
  end

  # POST /dashboards
  # POST /dashboards.json
  def create
    @dashboard = Dashboard.new(dashboard_params)

    respond_to do |format|
      if @dashboard.save
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully created.' }
        format.json { render :show, status: :created, location: @dashboard }
      else
        format.html { render :new }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboards/1
  # PATCH/PUT /dashboards/1.json
  def update
    respond_to do |format|
      if @dashboard.update(dashboard_params)
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @dashboard }
      else
        format.html { render :edit }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboards/1
  # DELETE /dashboards/1.json
  def destroy
    @dashboard.destroy
    respond_to do |format|
      format.html { redirect_to dashboards_url, notice: 'Dashboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
#    # Use callbacks to share common setup or constraints between actions.
  def set_dashboard
#      @dashboard = Dashboard.find(params[:id])
   end

    # Never trust parameters from the scary internet, only allow the white list through.
#    def dashboard_params
#      params.require(:dashboard).permit(:Date, :NewCardRegs, :DailyRxUsers, :DeviceRegistrations, :DeviceActivity, :PeopleScanning, :ItemsScanned)
#    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/daily_totals_helper.rb
module DailyTotalsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/daily_totals/_form.html.erb
<%= form_for(@daily_total, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @daily_total.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@daily_total.errors.count, "error") %> prohibited this daily_total from being saved:</h4>

      <ul>
      <% @daily_total.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :date, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :date, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :new_card_regs, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :new_card_regs, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :daily_rx_users, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :daily_rx_users, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :device_registrations, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :device_registrations, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :device_activity, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :device_activity, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :peoplescanning, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :peoplescanning, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :items_scanned, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :items_scanned, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/daily_totals/edit.html.erb
<div class="page-header">
  <%= link_to daily_totals_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @daily_total, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing daily_total</h1>
</div>

<%= render 'form' %>

app/views/daily_totals/index.html.erb
<div class="page-header">
  <%= link_to new_daily_total_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Daily total
  <% end %>
  <h1>Listing daily_totals</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Date</th>
            <th>New card regs</th>
            <th>Daily rx users</th>
            <th>Device registrations</th>
            <th>Device activity</th>
            <th>Peoplescanning</th>
            <th>Items scanned</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @daily_totals) do |daily_total| %>
            <td><%= daily_total.date %></td>
            <td><%= daily_total.new_card_regs %></td>
            <td><%= daily_total.daily_rx_users %></td>
            <td><%= daily_total.device_registrations %></td>
            <td><%= daily_total.device_activity %></td>
            <td><%= daily_total.peoplescanning %></td>
            <td><%= daily_total.items_scanned %></td>
            <td><%= link_to 'Show', daily_total %></td>
        <td><%= link_to 'Edit', edit_daily_total_path(daily_total) %></td>
        <td><%= link_to 'Destroy', daily_total, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/daily_totals/new.html.erb
<div class="page-header">
  <%= link_to daily_totals_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New daily_total</h1>
</div>

<%= render 'form' %>

app/views/daily_totals/show.html.erb
<div class="page-header">
  <%= link_to daily_totals_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_daily_total_path(@daily_total), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show daily_total</h1>
</div>

<dl class="dl-horizontal">
  <dt>Date:</dt>
  <dd><%= @daily_total.date %></dd>

  <dt>New card regs:</dt>
  <dd><%= @daily_total.new_card_regs %></dd>

  <dt>Daily rx users:</dt>
  <dd><%= @daily_total.daily_rx_users %></dd>

  <dt>Device registrations:</dt>
  <dd><%= @daily_total.device_registrations %></dd>

  <dt>Device activity:</dt>
  <dd><%= @daily_total.device_activity %></dd>

  <dt>Peoplescanning:</dt>
  <dd><%= @daily_total.peoplescanning %></dd>

  <dt>Items scanned:</dt>
  <dd><%= @daily_total.items_scanned %></dd>

</dl>

app/views/dashboards/get_usage.html.erb
<div class="page-header">
  <h1>WICShopper Usage Dashboard</h1>
</div>
<h3>This is the main dashboard that will be used by JPMA staff</h3>
<div class="container-fluid">
  <div class=jumbotron>
    <!--<div class=jumbotron><-->
    <%= form_tag update_usage_path do %>
      <div class="input-daterange" data-behaviour='datepicker' id="datepicker" >
        <%  @begin_date = Date.strptime(@begin_date, "%Y%m%d").strftime("%m/%d/%Y")%>
        <%  @end_date = Date.strptime(@end_date, "%Y%m%d").strftime("%m/%d/%Y")%>
        <%= label_tag :begin_date %>
        <%= text_field_tag :begin_date, @begin_date  %>
        <%= label_tag :end_date %>
        <%= text_field_tag :end_date,@end_date %>
      </div>
      <p> <%= submit_tag 'Refresh', class: "btn btn-primary" %> </p>
    <% end %>

    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
          <th>WIC Authority</th>
          <th>Card Registrations</th>
          <th>Daily RX Users</th>
          <th>Dev Registrations</th>
          <th>Dev Activity</th>
        </tr>
        </thead>
        <tbody>

        <p>
          <% @mrg.each do |rows| %>
            <tr>
              <td><%= rows["Name"] %></td>
              <td><%= rows["RegistrationCount"] %></td>
              <td><%= rows["UserCount"] %></td>
              <td><%= rows["DeviceRegistrations"] %></td>
              <td><%= rows["DeviceActivity"] %></td>
          <% end %>
          <tr>
            <th>Totals</th>
            <th><%= @total_registration_count %></th>
            <th><%= @total_user_count %></th>
            <th><%= @total_device_registrations_count %></th>
            <th><%= @total_device_activity_count %></th>
          </tr>
        </p>
      </table>
    </div>
  </div>

  <script type="text/javascript">
      $('#datepicker')
        .datepicker({
          todayHighlight: true,
          orientation: "bottom auto",
          autoclose: true,
    })
  </script>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("wicshopper_icon.png", :alt => "jpma_wicshopper_logo.png", class: "img_responsive"), root_path %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>Logged in as <strong><%= current_user.email %></strong>.</li>
          <li><%= link_to 'Edit profile', edit_user_registration_path %> | </li>
          <li><%= link_to "Logoout", destroy_user_session_path, method: :delete %> </li>
        <% else %>
          <li><%= link_to 'New User', new_user_registration_path %> | </li>
          <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <%= msg %>
    <% end %>
  <% end %>

  <%= yield %>
</div>
</body>
</html>